<?php

/**
 * @file
 * Secures, restricts and keeps track of downloads of boooks for the
 * Teupaga digital buddhist library
 */

/**
 * Implements hook_permission().
 *
 * Defines the permission to download books.
 */
function teupaga_downloads_permission() {
  return array(
    'download books' => array(
      'title' => t('download books'),
      'description' => t('Specifies who can download books'),
    ),
  );
}

/**
 * Implements hook_menu().
 *
 * Provides a menu entry for downloading books.
 */
function teupaga_downloads_menu() {
  $items['livres'] = array(
    'access arguments' => array('download books'),
    'type' => MENU_CALLBACK,
    'page callback' => 'teupaga_downloads_menu_callback',
  );
  return $items;
}

/**
 * Called when a download is attempted.
 */
function teupaga_downloads_menu_callback() {
  $args = func_get_args();
  array_unshift($args, "private");
  call_user_func_array("file_download", $args);
}

/**
 * Implements hook_file_download().
 *
 * Performs the book download itself.
 */
function teupaga_downloads_file_download($file) {
  global $user;
  watchdog('teupaga', 'teupaga_downloads_file_download: entering');
/*
  if ($_SERVER['SERVER_PORT'] != '443') {
    watchdog('teupaga', 'teupaga_downloads_file_download: non-secured download attempted. Blocked.');
    return -1;
  }
*/

  $filename = file_uri_target($file);
  watchdog('teupaga', "teupaga_downloads_file_download: trying to find item associated with file $filename");
  $query = new EntityFieldQuery;
  $results = $query
    ->fieldCondition('field_document_link', 'url', $filename, 'CONTAINS')
    ->execute();
  
  ob_start();
  var_dump($results);
  $resultsstr = ob_get_clean();
  file_put_contents('/tmp/debug.txt', $resultsstr);

  if ( count($results) < 1) {
    watchdog('teupaga', "teupaga_downloads_file_download: No match found for $filename.");
    return -1;
  }

  if ( count($results) > 1) {
    watchdog('teupaga', "teupaga_downloads_file_download: More than one match found for $filename.");
    return -1;
  }

  $user_id = $user->uid;
  watchdog('teupaga', "teupaga_downloads_file_download: user_id=$user_id");
  $download_date = time();
  $downloaded_item = 17; /* FIXME */

  $teupaga_download = entity_create(
    'teupaga_downloads',
    array(
      'user_id' => $user_id,
      'downlod_date' => $download_date,
      'downloaded_item' => $downloaded_item
    )
  );
  $teupaga_download->save();

  $mimetype = file_get_mimetype($file);
  $size = filesize($file);
  $name = mime_header_encode(basename($file));
  watchdog('teupaga', 'teupaga_downloads_file_download: leaving (success)');
  return array(
    'Content-type: ' . $mimetype,
    'Content-Length: ' . $size,
    'Content-Disposition: attachment; filename="' . $name . '"',
  );
}

/**
 * Implements hook_entity_info().
 */
function teupaga_downloads_entity_info() {
  $info = array();

  $info['teupaga_downloads'] = array(
    'label' => t("Teupaga download"),
    'plural label' => t("Teupaga Downloads"),
    'description' => t("Represents a download event for a Teupaga book"),
    'base table' => 'teupaga_downloads',
    'entity keys' => array('id' => 'download_id'),
  );

  foreach ($info as $entity_name => &$settings) {
    $settings['module'] = 'teupaga_downloads';
    $settings['entity class'] = 'Entity';
    $settings['controller class'] = 'EntityAPIController';
    $settings['views controller class'] = 'EntityDefaultViewsController';
    $settings['fieldable'] = TRUE;
    $settings['label callback'] = 'entity_class_label';
    $settings['uri callback'] = 'entity_class_uri';
  }

  return $info;
}

/**
 * Implements hook_entity_property_info_alter().
 */
function teupaga_downloads_entity_property_info_alter(&$info) {
  $info['teupaga_downloads']['properties']['user_id'] = array(
    'label' => t('User'),
    'description' => t("User downloading the content."),
    'type' => 'user',
    'schema field' => 'user_id',
  );
  $info['teupaga_downloads']['properties']['download_date'] = array(
    'label' => t("Date of download"),
    'description' => t("The date and time when the download occurred."),
    'type' => 'date',
    'schema field' => 'download_date',
  );
  $info['teupaga_downloads']['properties']['downloaded_item'] = array(
    'label' => t("Downloaded item."),
    'description' => t("The itemthat has been downloaded."),
    'type' => 'field',
    'schema field' => 'downloaded_item',
  );
}
